//Names: Batool, Christian, Inaya, Kevine
//Description: firebase_options --> File generated by FlutterFire CLI.
// Class: CSI CUE 2023

// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7XpJ45lR8ige16Aosu2EAvXj9FzRUJ4',
    appId: '1:181486033470:web:05bbafaff1674ef51f8f6f',
    messagingSenderId: '181486033470',
    projectId: 'bscjiaks',
    authDomain: 'bscjiaks.firebaseapp.com',
    databaseURL: 'https://bscjiaks-default-rtdb.firebaseio.com',
    storageBucket: 'bscjiaks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOPE5ltfuISVsmYaPliEsFmZSH6SEFpR8',
    appId: '1:181486033470:android:fe8372add198cde81f8f6f',
    messagingSenderId: '181486033470',
    projectId: 'bscjiaks',
    databaseURL: 'https://bscjiaks-default-rtdb.firebaseio.com',
    storageBucket: 'bscjiaks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5v4l2fl9PK52mDNczseIiNfPJaIADuA',
    appId: '1:181486033470:ios:18daa9dcd0274f671f8f6f',
    messagingSenderId: '181486033470',
    projectId: 'bscjiaks',
    databaseURL: 'https://bscjiaks-default-rtdb.firebaseio.com',
    storageBucket: 'bscjiaks.appspot.com',
    iosClientId: '181486033470-c1v634rocapmfops1hk36mi9b2303c8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.lsatPrepApp2',
  );
}
